trigger:
  branches:
    include:
      - main

pool:
  name: Default

variables:
- group: sampleapi-config

stages:

# ---------- BUILD ----------

- stage: Build
  displayName: Build .NET API

  jobs:
  - job: BuildJob
    steps:

    - template: templates/build-template.yml
      parameters:
        buildConfiguration: $(buildConfiguration)


# ---------- DEPLOY ----------

- stage: Deploy
  displayName: Deploy to IIS
  dependsOn: Build

  jobs:
  - deployment: DeployWeb
    environment: onprem-dev

    strategy:
      runOnce:
        deploy:
          steps:

          - template: templates/deploy-template.yml