# azure-pipelines.yml
trigger:
  branches:
    include:
      - main

# 👇 Microsoft-hosted agent (FREE TIER – 1800 mins/month)
pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

stages:
- stage: Build
  displayName: 'Build .NET API'
  jobs:
  - job: Build
    displayName: 'Restore, Build, Publish'
    steps:
    - task: UseDotNet@2
      displayName: 'Use .NET 8 SDK'
      inputs:
        packageType: 'sdk'
        version: '8.0.x'

    - script: dotnet restore
      displayName: 'Restore dependencies'

    - script: dotnet build --configuration $(buildConfiguration)
      displayName: 'Build solution'

    - script: dotnet publish --configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)/publish
      displayName: 'Publish app'

    - publish: $(Build.ArtifactStagingDirectory)/publish
      artifact: drop

- stage: Deploy
  displayName: 'Deploy to Azure App Service'
  dependsOn: Build
  jobs:
  - deployment: DeployWeb
    displayName: 'Deploy Web App'
    environment: 'sampleapi'
    strategy:
      runOnce:
        deploy:
          steps:
          - task: AzureWebApp@1
            displayName: 'Deploy to Azure Web App'
            inputs:
              azureSubscription: 'azure-conn-sampleapi'
              appName: 'sampleapi-lovekush-001'
              package: '$(Pipeline.Workspace)/drop'
