name: CI - Build & Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build application
      run: dotnet build --no-restore

    - name: Build Docker image
      run: docker build -t lovekush1702/sampleapi:latest .

    - name: Push Docker image
      run: docker push lovekush1702/sampleapi:latest